# Customers CALLS #
# Variables
@base_URL=http://localhost:3000/api/customers

get {{base_URL}}

###
@objId1=630f5f8adfbf74a02c75d8ff
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "name": "Customer X",
    "active": true,
    "email": "customerx@gmail.com", 
    "number": "125254"
}

###
@objId2=630f758d96eff5760b9cf9bd
put {{base_URL}}/{{objId2}}
Content-Type: application/json

{
    "name": "Customer Y",
    "active": false,
    "email": "customery@gmail.com", 
    "number": "125255"
}

###
@objId3=630f758d96eff5760b9cf9bd
delete {{base_URL}}/{{objId3}}
Content-Type: application/json
