# Products CALLS #
# Variables
@base_URL=http://localhost:3000/api/products
get {{base_URL}}

###
@objId1=628cd0773ce9cf812842cac0
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "name": "Macbook Air M2", 
    "code": "MBA9785"
}

###
@objId2=630f75b096eff5760b9cf9c5
put {{base_URL}}/{{objId2}}
Content-Type: application/json

{
    "name": "Macbook Pro M2", 
    "code": "MBP8759"
}

###
@objId3=630f75b096eff5760b9cf9c5
delete {{base_URL}}/{{objId3}}
Content-Type: application/json
